[font]
size = 17
normal = { family = "JetBrainsMono Nerd Font", style = "Medium" }

[window]
title = "Terminal"
dynamic_padding = true
resize_increments = true

[colors.primary]
foreground = "#dddddd"

[mouse]
hide_when_typing = true
